modLoader = "kotlinforforge"
loaderVersion = "[1,)"
issueTrackerURL = "${mod_github_url}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
displayUrl = "${mod_github_url}"
logo = "${mod_icon}"

[[dependencies.audio_navigation]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${kotlin_for_forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "fzzy_config"
type = "required"
versionRange = "[${fzzy_config_neoforge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "minecraft_access"
type = "optional"
versionRange = "[${minecraft_access_version},)"
side = "CLIENT"

[[mixins]]
config = "${common_mixins_file}"
