modLoader = "kotlinforforge"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/emassey0135/audio-navigation/issues"
license = "GPL-3.0"

[[mods]]
modId = "audio_navigation"
version = "${version}"
displayName = "Audio Navigation"
authors = "Elijah Massey"
description = '''
A mod that announces points of interest around the player, inspired by Soundscape
'''
#logoFile = ""

[[dependencies.audio_navigation]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.audio_navigation]]
modId = "kotlinforforge"
type = "required"
versionRange = "[1.16.0,]"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "audio_navigation-common.mixins.json"
