name: release
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload Fabric build
        run: "gh release upload ${{ github.event.release.tag_name }} fabric/build/libs/audio_navigation-fabric-${{ github.ref_name }}.jar"
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
      - name: upload NeoForge build
        run: "gh release upload ${{ github.event.release.tag_name }} neoforge/build/libs/audio_navigation-neoforge-${{ github.ref_name }}.jar"
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
